version: '3.8'

services:
  db:
    image: postgres:17
    container_name: workout_backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: workout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    networks:
      - workout-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d workout_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend: 
    build: ./server/app
    depends_on:
      db:
        condition: service_healthy
    environment: 
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/workout_db
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    volumes:
      - ./server/app:/app
    networks: 
      - workout-network
    command: python main.py

  client:
    build: ./client
    depends_on:
      - backend
    ports:
      - "3000:5173"
    volumes:
      - ./client/:/app
      - /app/node_modules
    networks:
      - workout-network
    environment:
      - VITE_API_URL=${VITE_API_URL}

networks:
  workout-network:
    driver: bridge

volumes:
  postgres_data:
